### ISSUE TITLE
多人模式用不了

### ISSUE THREAD

**Issue by Originsin** [yunke120/zzu-jksb#1]
共有5个人的信息，但是只能打卡上第一个人的，其他人的打不上。项目正常运行。

**Comment by yibingbing120** [comment]
已收到反馈。准备进行多账号测试

**Comment by yunke120** [comment]
已收到反馈。准备测试多账号

**Comment by yunke120** [comment]
### 双人测试
可使用
![image](https://user-images.githubusercontent.com/56856909/202606657-8d82ea3d-84a6-4e1e-89c8-e7f6d14721c3.png)

**Comment by Originsin** [comment]
> ### 双人测试
> 可使用 ![image](https://user-images.githubusercontent.com/56856909/202606657-8d82ea3d-84a6-4e1e-89c8-e7f6d14721c3.png)

OKOK，是我添加的人太多了

**Comment by yunke120** [comment]
建议一个GitHub账号只挂载一个或两个，同一IP登录多次会被限制，出现登录不上的情况，第二天会恢复正常
